@startuml UML

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

class Flight {
  flight_number
  departure_date
  arrival_date
  effective_arrival_date
  effective_departure_date
  fuel_consumption
}

class Airport {
  airport_code_IATA
  name
  address
  country
  city
  latitude
  longitude
  price_cents_euro_per_month
}

class Airplane {
  model
  fuel_capacity
  brand
  price_cents_euro
  baggage_max_weight_kg
  baggage_max_per_passenger
  baggage_allowed_dimensions_cm2
}

class MaintenanceHistory {
  maintenance_date
  result
  cost_cents_euro
}

class Employee {
  first_name
  last_name
  job
  hire_date
  salary_cents_euro
}

class Passenger {
  first_name
  last_name
}

class Ticket {
  price_cents_euro
}

class Customer {
  email
  password
}

class Seat {
  seat_number
  class
}

class Reservation {
  reservation_number
  reservation_date
}

class Incident {
  number
  description
  date
}

class Baggage {
  weight_kg
  dimensions_cm2
}

Airplane "1..1" -- "0..n" Flight : Fly
Seat "1..*" -- "1..1" Airplane : Belongs
Employee "1..*" -left- "1..1" Flight : Fly
Passenger "1..1" -- "1..*" Ticket : Owns
Ticket "0..*" --- "1..1" Flight : Belongs
Flight "0..*" -- "1..*" Seat : Taken
Reservation "1..1" -- "1..*" Ticket : Buy

MaintenanceHistory "0..*" -right- "1..1" Airplane : Happen

Flight "1..1" -right- "0..*" Incident : Happen

Flight "1..1" -- "0..*" Airport : Departure
Flight "1..1" -- "0..*" Airport : Arrival

Customer "1..1" -- "0..*" Reservation : Book

Ticket "1..1" -- "0..*" Baggage : Includes

@enduml
