@startuml UML

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

class Flight {
  flight_number
  departure_date
  arrival_date
  effective_arrival_date
  effective_departure_date
}

class Airport {
  airport_code_IATA
  name
  address
  country
  city
  latitude
  longitude
}

class Airplane {
  model
  fuel_capacity
  brand
  last_maintenance_date
}

class Employee {
  first_name
  last_name
  job
  hire_date
  salary
}

class Passenger {
  first_name
  last_name
}

class Ticket {
  price_cents
  price_currency
}

class Seat {
  seat_number
  class
}

class SeatTaken {

}

class Reservation {
  reservation_number
  reservation_date
}

class Incident {
  incident_number
  description
}

Airplane "1..1" -- "0..n" Flight : Fly
Seat "1..*" -- "1..1" Airplane : Belongs
Employee "1..1" -left- "1..1" SeatTaken
Passenger "1..1" -- "1..1" Ticket
Ticket "0..1" -right- "1..1" SeatTaken
SeatTaken -- "0..1" Seat : Taken
Reservation "1..1" -- "1..*" Ticket : Buy
SeatTaken "1..*" -- "1..1" Flight

Flight "1..1" -right-- "0..*" Incident

Flight "1..1" -left- "0..*" Airport : Departure
Flight "1..1" -left- "0..*" Airport : Arrival

@enduml
