name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    env:
      DO_NOT_TRACK: "1"
    steps:
      - uses: "actions/checkout@v4.2.2"

      - uses: "pnpm/action-setup@v4.1.0"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.2.0"
        with:
          node-version: "22.x"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm clean-install"

      - run: "node --run lint:editorconfig"
      - run: "node --run lint:prettier"
      - run: "node --run lint:typescript"
